{{- if eq .Values.deploymentType "rollout-bluegreen"}}

apiVersion: argoproj.io/v1alpha1

kind: Rollout

metadata:        
  name: {{ .Release.Name }}-bluegreen

spec:                
  replicas: {{ .Values.replicaCount }}  

  strategy:
    blueGreen:
      activeService: gitops-active
      previewService: gitops-preview
      autoPromotionEnabled: false

  selector:          
    matchLabels:  
      app: {{ .Release.Name }}   
  template:          
    metadata:    
      labels:
        app: {{ .Release.Name }}
    spec:          
      containers:
      - name: {{.Chart.Name}}      
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"          
        imagePullPolicy: {{.Values.image.pullPolicy}}
        ports:          
        - containerPort: 8080

      resources: {{- toYaml .Values.resources | nindent 10}}


{{- end }}