#Defines which Kubernetes API
apiVersion: apps/v1

kind: Deployment          #Deployment = manager that runs your app and keeps it alive

metadata:                 #This is how Kubernetes identifies it
  name: gitops-app        #This name will become Label of the Docker object 

spec:                                 # actual instruction starts here
  replicas: 1                         # define number of copies
  selector:                           # this connet deployment to pods 
    matchLabels:                      # matches all the lable below to apply this deployment to pod
      app: gitops-app                 # label of existing container
  template:                           # pod template 
    metadata:                         # container created under this will have same label as given below
      labels:
        app: gitops-app
    spec:                             # define container details
      containers:
      - name: gitops-app              # container name
        image: wiesslogia/gitops-app:latest           # docker img created
        imagePullPolicy: Always       # use local image
        ports:                        # port to run app
        - containerPort: 8080

      resources:
        requests:
          cpu: "5m"
          memory: "20Mi"
        limits:
          cpu: "15m"
          memory: "25Mi"