apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/Wiesslogia/Production-Grade-DevSecOps-GitOps-Pipeline.git
    targetRevision: main
    path: gitops-chart   
    helm:
      valueFiles:
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true