deploymentType: deployment

replicaCount: 1

image:
  repository: wiesslogia/gitops
  pullPolicy: IfNotPresent
  tag: "3368f82d769694ed9e5ce516bae4e1aabd0c9e03"

resources: 
  requests:
    cpu: "10m"
    memory: "50Mi"
  limits:
    cpu: "25m"
