replicaCount: 1

image:
  repository: wiesslogia/gitops
  pullPolicy: IfNotPresent
  tag: "ef7bac427993cbff137bfd78a2b42abe8713cbbd"

resources: 
  requests:
    cpu: "10m"
    memory: "50Mi"
  limits:
    cpu: "25m"
