replicaCount: 1

image:
  repository: wiesslogia/gitops
  pullPolicy: IfNotPresent
  tag: "a1ad770ff3ef78dab209fe882071f50e5e763c70"

resources: 
  requests:
    cpu: "10m"
    memory: "50Mi"
  limits:
    cpu: "25m"
